# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# MARKDOWN ********************

# # Load Sales Data
# 
# Generates dummy sales data and loads it to the **DW** warehouse.
# 
# **Parameters:**
# - `rows_to_generate` - Number of sales rows to create (default: 100)
# 
# **Setup:**
# - **Attach this notebook to StagingLakehouse** (separate from MetadataLakehouse)
# 
# **Note:** 
# - PySpark generates data and stages in StagingLakehouse (sales_staging table)
# - T-SQL Copy activity loads from lakehouse to warehouse

# CELL ********************

from pyspark.sql import SparkSession
from pyspark.sql.functions import current_timestamp, expr, lit
from pyspark.sql.types import StructType, StructField, StringType, DecimalType, TimestampType
from datetime import datetime, timedelta
import random

# PARAMETERS CELL ********************

# Number of sales rows to generate
rows_to_generate = 100

# MARKDOWN ********************

# ## Generate Dummy Sales Data

# CELL ********************

spark = SparkSession.builder.getOrCreate()

# Generate date range (last 30 days)
base_date = datetime.now() - timedelta(days=30)

# Create dummy sales data
sales_data = []
for i in range(rows_to_generate):
    days_offset = random.randint(0, 30)
    sale_date = base_date + timedelta(days=days_offset)
    amount = round(random.uniform(10.0, 1000.0), 2)
    
    sales_data.append({
        'sale_id': None,  # Will be generated by warehouse
        'sale_date': sale_date.strftime('%Y-%m-%d'),
        'amount': float(amount),
        'created_at': datetime.now()
    })

# Define schema explicitly
schema = StructType([
    StructField("sale_id", StringType(), True),
    StructField("sale_date", StringType(), True),
    StructField("amount", DecimalType(10, 2), True),
    StructField("created_at", TimestampType(), True)
])

# Create DataFrame
df_sales = spark.createDataFrame(sales_data, schema=schema)

print(f'Generated {df_sales.count()} sales records')
df_sales.show(10)

# MARKDOWN ********************

# ## Stage Data in Lakehouse
# 
# Writes sales data to a staging table in the attached lakehouse.
# A T-SQL script will then load from lakehouse to DW warehouse.

# CELL ********************

# Write to staging table in lakehouse (overwrite mode)
staging_table = "sales_staging"

df_sales.write.format("delta") \
    .mode("overwrite") \
    .saveAsTable(staging_table)

print(f'✓ Staged {rows_to_generate} sales records to {staging_table}')
print(f'\n📋 Next step: Run T-SQL script to load from lakehouse to DW:')
print(f'   INSERT INTO DW.dbo.Sales (sale_id, sale_date, amount, created_at)')
print(f'   SELECT NEWID(), sale_date, amount, created_at')
print(f'   FROM {staging_table}')

# CELL ********************

print('=' * 60)
print('✓ Sales data staging complete!')
print('=' * 60)
print(f'\nStaging table: {staging_table}')
print(f'Rows: {rows_to_generate}')
print(f'\n⚠️  Remember to execute the SQL Copy script to load to DW warehouse')
